### ISSUE TITLE
Terminal spans most window height - after upgrading to macOS Ventura

### ISSUE THREAD

**Issue by pax** [marta-file-manager/marta-issues#1017]
After upgrading to Ventura, opening the terminal fills most of Marta's window height.

![Screenshot 2023-09-16 at 00 57 55](https://github.com/marta-file-manager/marta-issues/assets/116795/904290ac-a255-43d0-b937-c48f4a76571c)

MBP M1 14" 2021 - MacOS Ventura 13.5.2

*hoping it's not abandonware :/

**Comment by Stramon1um** [comment]
Hi, I noticed a "similar" behaviour but without opening the terminal. When I reopen Marta's window, and I enter in a folder, this is what happens:
![image](https://github.com/marta-file-manager/marta-issues/assets/11859033/92d45c65-7b02-46a3-9d77-63946fe56c19)

it's like a shift and after reclicking, it returns to normality. After entering in a new folder, it does that again so I mostly missclick on the wrong folder due to the shifting of the list.

It started doing this only after upgrading to Sonoma, no matter how often I close Marta or restart the pc

**Comment by yanex** [comment]
@Stramon1um It seems like a different issue which I failed to reproduce on Sonoma 14.1 (23B74). Do you know a stable reproduction scenario?

**Comment by Stramon1um** [comment]
> @Stramon1um It seems like a different issue which I failed to reproduce on Sonoma 14.1 (23B74). Do you know a stable reproduction scenario?

Hi, thanks for the replay. I updated my mac yesterday night to Sonoma 14.1 and it seems that the "glitch" disappeared, so I don't know, maybe it was just on my pc 🤷‍♂️

I will let you know if the issue comes back 😉

**Comment by pax** [comment]
somewhat related: https://github.com/marta-file-manager/marta-issues/issues/998 (_Titlebar height after plug in ext. monitor_)

**Comment by centur** [comment]
Is there any settings for 0.8.1 version that we can use to mitigate this problem ? Came here to find a solution and it's great to see it will be fixed in next release, but I use marta's terminal a lot and happy to band aid my version while waiting for proper release of 0.8.2
I'm on Sonoma 14.1.1 and the bug is still there.

**Comment by vedmant** [comment]
I have the same problem, is there any setting for default terminal height? Or maybe make it remember last height? (Sonoma 14.2.1 (23C71))
