### ISSUE TITLE
Any way to automatically use F keys without "fn" key when Marta is active?

### ISSUE THREAD

**Issue by vedmant** [marta-file-manager/marta-issues#1033]
Following this conversation https://news.ycombinator.com/item?id=16719745

I still want to use F keys for Marta, but it's not convenient that I need to press fn key all the time, I was thinking if there is a way for Marta to kind of press fn key for me?

There is an app for this https://github.com/Pyroh/Fluor and it works fine, but would be nice to have this feature built in.

**Comment by yanex** [comment]
As I understand, the way Fluor does this is pretty [invasive](https://github.com/Pyroh/Fluor/blob/1a14f1b5cec9816470427bfb94d38698a2a7c1d5/Fluor/Misc/FKeyManager.swift#L57). Basically, the application changes the system-global setting each time some new application is activated.
Even if desired, I believe such functionality should be a part of a special application (such as Fluor), rather than a file manager.
