### ISSUE TITLE
Look up: Prefix modifiers for regular expression search

### ISSUE THREAD

**Issue by gawashburn** [marta-file-manager/marta-issues#145]
It would also be nice to have prefix modifiers for regular expression searches on file names and contents.  However, again this may not be practical depending on what the Spotlight API exposes.

**Comment by gawashburn** [comment]
Nevermind, I had missed #119 which I assume covers this.

**Comment by yanex** [comment]
I don't think so, regular expressions allow much more than wildcards.

**Comment by yanex** [comment]
Unfortunately, it's not possible to implement a regular expression search in the Look Up action as Spotlight indices don't provide such functionality. Querying all existing entries and filtering them on the Marta side is not very performant, I suppose.
However, a wildcard search is supported in Spotlight (#119), and it will be possible to use wildcard patterns since Marta 0.8.1.
Moreover, In later versions of Marta, a fully-fledged file search dialog will certainly allow using regular expressions.
