### ISSUE TITLE
Quick Select: Do not reset selection

### ISSUE THREAD

**Issue by monouser7dig** [marta-file-manager/marta-issues#216]
workflow:
select some PDF that contain a certain string and open them

how I tried:
search for the string, all PDFs show up cause I set `"filterMatchedItems": true`

(a small nit in `"filterMatchedItems": true` + `"activateOnAnyCharacter": false` 
I hit `/` to start searching and then `\` to perform a substring search but when I press `\` the search list is empty and is only populated when I start typing)

I would now like to `shift select` some of those but as soon as I do, the `MatchedItems List` disappears

I'd suggest to keep it until `esc` is pressed

**Comment by yanex** [comment]
So looks like there are two issues here.
The first one is that `\` only acts as a filter while it should be completely ignored (no items should be filtered out) until at least one substring symbol is provided. The same is for `/`.
The second one is that Quick Select resets the selection.

**Comment by monouser7dig** [comment]
> So looks like there are two issues here.

yes that is accurate

**Comment by yanex** [comment]
(See also "Quick Select: Do not filter out elements on "/" or "\" query #218").

**Comment by warpkanal** [comment]
Even more worse, this selection resetting is also affecting drag&drop operations: recently in a huge directory: I typed some characters to filter for the file I was looking for, then I wanted to drag it to another application, however a different file was dragged to the other application!
Why? Because on pressing the mouse button (to start dragging), selection is reset and you actually drag suddenly the item that would appear in that place if you had hit `Esc` before.
This makes filtering somewhat dangerous...

**Comment by warpkanal** [comment]
This bug is really driving me nuts: quick filter drag, mistake happened:
![dd_broken](https://user-images.githubusercontent.com/3669157/37242029-d9f291ea-2462-11e8-8a62-566bb5a548c1.gif)

**Comment by yanex** [comment]
@warpkanal Yes, this is a major bug indeed. I will fix it in the scope of 0.5.1 (hopefully, will be released quite soon after 0.5).
