### ISSUE TITLE
Async: Operation can't be paused if not started yet

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#225]

**Comment by monouser7dig** [comment]
It can not be paused/ aborted using the buttons if the SMB volume is disconnected.
(I wake up my mac and the connection is somehow lost, happens frequently, the explorer (finder as well) still shows the folder but when you attempt to access it you get a warning saying the folder is not connected)
In this case marta can not abort the copy operation

**Comment by yanex** [comment]
@monouser7dig Does it fail to pause when you copying local files to the SMB volume? Or vice versa?

Also, am I understand you right that you ran the "Copy action", then paused it, put the Mac to the sleep mode (or disconnected SMB volume some other way). Now you press "Resume", and after that you can't pause/abort the pending operation?

**Comment by monouser7dig** [comment]
I was not actually doing any file operations.

I'm in a VPN and have connected to the SMB, went to east something, came back, woke the mac, tried to copy something and could not cancel/ pause, as it turned out, the SMB volume was not reachable anymore (had been disconnected in some way while my mac went to sleep)

**Comment by yanex** [comment]
@monouser7dig I reproduced this with .dmg files: #229.

**Comment by monouser7dig** [comment]
So this is actually not that much of an edgecase afterall, nice!
