### ISSUE TITLE
Provide a lightweight version of API for simple plugins

### ISSUE THREAD

**Issue by yanex** [marta-file-manager/marta-issues#254]
Marta has a public API that works seamlessly with all core components, but writing a plugin requires installing Xcode, and, as Swift ABI is not stable, the new version of Marta can break compatibility with existing plugins.

While the second problem should go away as the next Swift version is released, the learning curve is quite steep. We need to lower it to make plugin development easier, so Marta should support lightweight plugins written in a script language (e.g. Lua).

Such "lightweight" plugin code would not need to be compiled, placing it into the "Plugins" directory should be enough.

API subset needed to be supported:
- Actions
- List model modification
- Configuration
- File system handlers

**Comment by nanoant** [comment]
@yanex Hi, if I could suggest something. I would strongly advise you to use Python or MicroPython. Python can be easily embedded and with zipped standard library it weights maybe 5-7MB altogether.
This would be somewhat similar to what Sublime Text offers and will definitely reach more developers than Lua (or LuaJIT) which are great too, but Python is just so popular nowadays.

**Comment by yanex** [comment]
When I thought about what language would be good to base Marta API on, I made a short list of requirements:

- Popularity. It should be easy to find books, articles, and answers to common questions.
- Ecosystem support. Libraries, build tools, dependency repositories, IDEs – all of this should exist.
- Maturity. Languages that don't change a lot over time are preferred. Dealing with breaking changes is a pain as it will break all the existing plugins.
- API stability. Swift API is terrible not only because of the steep learning curve. It's extremely hard to evolve the API without breaking backward compatibility. Also, each Swift update breaks it for sure.
- Simplicity. It should be possible to learn a language in a short period. Also, as a plugin is often a short code snippet, common things should be as easy as possible.
- Compactness. An interpreter (or a compiler?) itself and its standard library shouldn't be heavy as it affects the resulting application size.
- Non-invasiveness. A language should be easily embeddable. It should not change a global environment or require the host application to be (re-)written in a particular way. As plugins will run in the isolated 'containers', these containers should be lightweight.
- Hot reload. Not critical, but nice to have.

I didn't mention the 'performance' requirement – of course, a faster language is better, though it's not an ultimate goal as many languages allow to write performance-critical code in a native language, such as C.

Python definitely is a popular language. However, it fails to satisfy some of the other goals above. Also, if I would choose the most popular programming language, it would definitely be JavaScript, as it's a clear winner here.

1. CPython distribution is heavy. Not only it weights a lot, but I'm also concerned about the RAM usage.
2. MicroPython isn't an alternative as it has many [incompatibilities](http://docs.micropython.org/en/latest/genrst/index.html) with CPython, and it only supports Python 3.4. This together breaks the ecosystem support – I can't guarantee that the popular libraries will still work with µP.
3. There're a lot of things going in Python, and I personally think the language is a bit over-complicated.
4. Python wasn't designed as an embeddable language. It exposes a lot of internal stuff and [modifies](https://docs.python.org/2/c-api/init.html#c.Py_Initialize) the global state. The Python C API scope is tremendous.

On the contrary, Lua perfectly matches all the requirements. I can't say I liked all design decisions of the language, though I experimented with it a bit – and I must say Lua allows to create a simple API in a pretty safe manner.

**Comment by nanoant** [comment]
> CPython distribution is heavy. Not only it weights a lot, (...)

Python embeddable package is 2MB for minimal standard library as `python37.zip` and CPython runtime which is also ~6MB depending on platform, see:
* https://blogs.msdn.microsoft.com/pythonengineering/2016/04/26/cpython-embeddable-zip-file/
* https://docs.python.org/3/using/windows.html#the-embeddable-package
* https://www.python.org/ftp/python/3.7.0/python-3.7.0-embed-amd64.zip

Good example of embedding Python is Sublime Text, take a look into `Sublime Text.app/Contents/MacOS`. I believe Python is statically linked (since it is BSD-like license) into `plugin_host` which is 8MB. Altogether with standard library zip is 10MB.

> (...) but I'm also concerned about the RAM usage.

RAM usage depends on the script/program itself, Python is not inherently using much RAM, start `python` and see yourself. Python structures are neither that RAM hungry. And btw. python is widely used in Linux distributions and its components.

But badly written program can eat your RAM indeed. Therefore Sublime Text uses `plugin_host` that keeps the plugins in separate process, so any badly written plugin will not tear down the app itself. I think this is really wise approach.

> Python wasn't designed as an embeddable language. It exposes a lot of internal stuff and [modifies](https://docs.python.org/2/c-api/init.html#c.Py_Initialize) the global state. There's a global interpreter  lock. The Python C API scope is tremendous.

That's completely true. However again I can see many applications using Python as embedded plugin environment and they work just fine.

> On the contrary, Lua perfectly matches all the requirements. I can't say I liked all design decisions of the language, though I experimented with it a bit – and I must say Lua allows to create a simple API in a pretty safe manner.

Completely agree with that. Lua and LuaJIT (which I would jump straight to if I was to use Lua) match your constraints perfectly. Another thing for LuaJIT is FFI which allows calling C API directly from Lua script, e.g. https://github.com/nanoant/glua

My only point is that there are at least 1000x more people knowing Python than Lua, and I really expect people anyway asking why not Python anyways, and simply making Marta work with Python gives the whole effort much higher chances to succeed. So in the end it is kind of a trade-off.

But whatever you choose, Python or Lua it will be a good choice in the end :)

**Comment by eugenesvk** [comment]
These are great design choices for the simple plugins (as stated in the title), but what about more complex plugins?
You mention
> You can also write the whole plugin in a native language and use Lua solely as a glue between Marta and your functionality. Lua API calls can be incapsulated, so you will deal not with lua_State, but with ActionContext and ListModel.

But is there a way to achieve that native language bliss (to avoid that multi-dozens-Gb XCode monstrosity) without the lua glue?
