### ISSUE TITLE
Publish list of action names/ids to use in keybinding section

### ISSUE THREAD

**Issue by anadale** [marta-file-manager/marta-issues#283]
My original intent was to bind "Swap panes" action to Control/Command+U keys, but I wasn't able to find name or id for this action. It would be great to publish a list of all actions that are available for keybinding.

**Comment by yanex** [comment]
In recent versions of Marta, pressing `Option/Alt` key in the Actions panel will show identifiers for all actions. So it seems for me that this issue is kind of obsolete.

<img width="629" alt="screenshot 2019-02-15 at 04 46 41" src="https://user-images.githubusercontent.com/95996/52829178-c6eefc00-30dc-11e9-85b2-028f3caf5a12.png">
