### ISSUE TITLE
Display tags  in the column

### ISSUE THREAD

**Issue by Dellu** [marta-file-manager/marta-issues#407]
Editing the column to add **tags** is not able to display a **tags** column.

**Comment by yanex** [comment]
If you are about the color tags, in the older versions of Marta tags were displayed in the separate column called `label`. Now the color tags are displayed right in the file name column.
(In fact Marta 0.5.3 has a bug that broke the color tag displaying. This will be fixed in 0.6).
As about generic text tags, this is not yet supported. Please follow this issue https://github.com/marta-file-manager/marta-issues/issues/443.
