### ISSUE TITLE
Possible to create custom commands via config.json instead of a plugin

### ISSUE THREAD

**Issue by rkpatel33** [marta-file-manager/marta-issues#419]
Is it possible to write or configure a custom commands in the config file instead of creating a plugin? I am not at all familiar with macOS bundles so its a big learning curve for me. What I would like to do is something simple: create 2 commands the will set sort order directly, and tie them to shortcuts. The are my two main views and I am constantly switching between them. I looked at gadgets but seems not quite possible with that.

1) set `pane.isAscending=false` and `pane.sortingColumn=modified`

2) set `pane.isAscending=true` and `pane.sortingColumn=extension`

Love the application btw!

**Comment by yanex** [comment]
Hello, @rkpatel33! I don't think that configuration files are good enough for this because of the lack of extensibility. What we are going to have instead is lite plugins written in Lua (see https://github.com/marta-file-manager/marta-issues/issues/254). Writing light plugins will not require you to install Xcode and learn packaging and all that stuff.

**Comment by rkpatel33** [comment]
That would be awesome as well. Do you have any rough timeline for working on this? Just curious.
