### ISSUE TITLE
0.6 RC: Copy pane changes color after animation

### ISSUE THREAD

**Issue by yole** [marta-file-manager/marta-issues#447]
Mac OS Mojave, light theme. When you press F5, the Copy pane slides down with dark gray background and then changes to light gray.

**Comment by yanex** [comment]
Thanks! Fixed.

**Comment by yanex** [comment]
Unfortunately, I could not reproduce this behavior on several machines with Mojave.
I've attached a video how this should look like.

[447.mov.zip](https://github.com/marta-file-manager/marta-issues/files/2634673/447.mov.zip)

Please try to restart your computer as this may be a macOS bug.

**Comment by yanex** [comment]
Also, what exact macOS version do you have?

**Comment by yole** [comment]
10.14.1. Restart does not help.

**Comment by yanex** [comment]
@yole Can you please check if the bug is fixed in any of the attached versions? If not, is it possible to make a screenshot/video of how it looks like?

[a.zip](https://github.com/marta-file-manager/marta-issues/files/2640717/a.zip)
[b.zip](https://github.com/marta-file-manager/marta-issues/files/2640755/b.zip)
[c.zip](https://github.com/marta-file-manager/marta-issues/files/2640836/c.zip)

**Comment by yole** [comment]
Unfortunately neither of these builds helps. I've attached a screen recording: 
[copy-bug.mov.zip](https://github.com/marta-file-manager/marta-issues/files/2649262/copy-bug.mov.zip)

**Comment by yanex** [comment]
Oh, this looks really bad. :(
I made an another attempt to fix the background, please check this version: [d.zip](https://github.com/marta-file-manager/marta-issues/files/2650501/d.zip).

Also,
1. Does this reproduce on other sheet dialogs, such as "Display mode…" or "Edit columns…"?
2. Does this reproduce on light themes (such as "Classic")?
3. What happens if you set this configuration option?
```
{
    "behavior": {
        "controlStyle": "light"
    }
}
```
4. And this option?
```
{
    "behavior": {
        "sheetDialogs": false
    }
}
```
5. What happens if you switch to the dark theme in macOS?
6. Do you use any other window-managing utilities besides Moom? I think all applications of this kind should be listed in "System Preferences -> Security & Privacy -> Privacy -> Accessibility".

**Comment by yanex** [comment]
Also, does the bug reproduce in the current Marta version (0.5.3.1)?

**Comment by yole** [comment]
d.zip doesn't help :(
1) Yes, it does reproduce on other dialogs.
2) Classic theme looks good, the background color of the sheet stays the same.
3) Looks good too.
4) There's no animation, so the color doesn't change.
5) The problem looks exactly the same in dark theme.
6) The list shows Alfred 3, Dropbox, IDEA, iTerm, Moom and Telegram.

**Comment by yole** [comment]
0.5.3.1 works fine. The Copy dialog background is dark and stays dark during the animation.

**Comment by yanex** [comment]
Here are another two versions.

The first one (`e.zip`) allows setting different control styles. Please try `dark`, `vibrantLight`, `vibrantDark`, `default`. It's better to restart Marta after changing the control style.

```
{
	"behavior": {
		"controlStyle": "dark"
	}
}
```

The second one is built against the older version of macOS SDK.

[e.zip](https://github.com/marta-file-manager/marta-issues/files/2663845/e.zip)
[f.zip](https://github.com/marta-file-manager/marta-issues/files/2664168/f.zip)

**Comment by yanex** [comment]
And one more version:
[h.zip](https://github.com/marta-file-manager/marta-issues/files/2681311/h.zip)

**Comment by yanex** [comment]
@yole Is the bug still actual in Marta 0.6.1 and the actual version of macOS 10.14?

**Comment by yole** [comment]
This works correctly in 0.6.1.

**Comment by yanex** [comment]
@yole Perfect. Thanks!
