### ISSUE TITLE
No keyboard navigation in Target already exists window

### ISSUE THREAD

**Issue by krupenja** [marta-file-manager/marta-issues#477]
1. Try to copy/move a file or folder which already exists in the folder open in the opposite pane.

In the resulting Target already exists window, pressing Tab or arrow keys does nothing. So choosing anything but the default action (Replace) is possible only using mouse.

**Comment by krupenja** [comment]
Hmm, I am still getting this in 0.6.2. Tried pressing both Tab and arrow keys but nothing happens - so still have to use mouse to select anything besides replace. Am i missing something?

**Comment by yanex** [comment]
On macOS, pressing the Tab key does not chagne button focus, as in Windows. Instead of that, you can press key alternatives.

For example, in the "Directory already exists" dialog you can press:
- `Return` to Replace;
- `M` to Merge;
- `R` to Retry;
- `S` to Skip;
- `A` to Abort.

In "File already exists" dialog you can press:
- `Return` to Replace;
- `Opt+N` to Replace if newer;
- `Opt+S` to Replace if size is different;
- `R` to Retry;
- `S` to Skip;
- `A` to Abort.

**Comment by auduchinok** [comment]
> On macOS, pressing the Tab key does not chagne button focus, as in Windows.

It's just not enabled by default, but there's definitely a way to use Tab to switch focus this way. `Ctrl+F7` toggles this option.
