### ISSUE TITLE
'core.preview' does not work inside of a zip file, but 'core.edit' does.

### ISSUE THREAD

**Issue by gawashburn** [marta-file-manager/marta-issues#51]
I would be less surprised here if it both actions failed, instead of just 'core.preview'.  

I'm not sure if this applies to all plugins providing virtual file systems.

**Comment by yanex** [comment]
"Preview" action shows the default macOS preview dialog, and it works only for the local file system.
Even if available for non-local FSs, *Preview* requires the file contents to be locally available (an image can't be previewed without downloading or unpacking), so it would be very inefficient.
Instead of supporting *Preview* for all VFSs, we can add the new *Details* action which would display all available information, including the preview if it's available.

**Comment by gawashburn** [comment]
Okay, I had assumed that the VFS was already unpacking files to a temporary location as needed, otherwise the `core.edit` or `core.open` actions wouldn't be succeeding on VFS files?

**Comment by yanex** [comment]
Yes, "Edit" caches the file.
But "Preview" is quite an another story. You can open the "Preview" window, go back to the file list, select any other file, and the preview will be automatically updated. This is how it works in Finder (and in Marta). Caching files on each cursor movement is very expensive, so it is supported only for local files.
