### ISSUE TITLE
Preserve and restore the last navigation session between restarts

### ISSUE THREAD

**Issue by gasparetto** [marta-file-manager/marta-issues#547]
Feature request. Preserve and restore the last navigation session (window position and current selected directories) between application restarts, or at least between the closing and reopening of the main window.

**Comment by yanex** [comment]
Hello @gasparetto! Marta should preserve state when the application is closed. If it doesn't work for you, please let me know.
However, I found out that after closing all windows, pressing on a Marta dock icon shows a window with default state (size / active directories). This will be fixed in 0.6.3.
