### ISSUE TITLE
Provide a way to donate towards Marta development

### ISSUE THREAD

**Issue by ay4** [marta-file-manager/marta-issues#562]

**Comment by ay4** [comment]
With such amazing features this must be an obvious requirement.

**Comment by haakonstorm** [comment]
- I'm currently considering how active development really is on this project.
- Marta as it currently stands is almost ready for prime time, but there is very little developer feedback and no way to see commits to the kode in the project
- Many issues have been left uncommented by the devs for many many months. Usually this is a sign the project is more or less abandoned. This would be very sad, because Marta is already awesome, and *fast* (especially compared to e.g. fman).

**Comment by yanex** [comment]
Hello, @ay4, @haakonstorm and everyone!

> I'm currently considering how active development really is on this project

I have been quite busy because of relocation (I moved to Japan some time ago). It took enormous time to settle out. Fortunately, it's almost over by now, so now I'm working on Marta much more regularly. Marta 0.7 is almost production-ready. Hopefully, I will publish either an RC or just a release next week.

> Many issues have been left uncommented by the devs for many many months

I admit I missed a couple of new issues. However, all tagged issues have been seen by me. Usually, I attach a "bug" or a "feature" label and eventually assign some release milestone. For general questions about implemented features, such as #528, I post answers directly.
However, the current feedback may not be sufficient in some cases. I will be more active for bugs as well. Thanks for the suggestion!
If you have some unanswered question, please feel free to ping me about it.

> Provide a way to donate towards Marta development

As I stated in the [first blog post](https://marta.yanex.org/introducing-marta), Marta will eventually become a paid product. I feel I don't want to sell half-baked software, so I will spend a bit more time polishing things here and there.
However, I get questions about donations all the time. So I think some platform like Patreon will be the optimal choice. I will investigate available options, and probably will introduce something on the time of the Marta 0.7 release.

**Comment by yanex** [comment]
So here we are :) https://www.patreon.com/marta_file_manager

Let me humbly notify you as you showed interest in supporting Marta.
@ay4 @haakonstorm @politicus @marcinbiegun @krupenja
