### ISSUE TITLE
Some issues/questions combined

### ISSUE THREAD

**Issue by haakonstorm** [marta-file-manager/marta-issues#567]
Sorry for combining these in to one post, please let me know if you want me to split these up:

1. **bug** Open `Applications` on your left and `Downloads` on your right pane. Say you have ´Xcode Beta.app` in your right pane selected. 
  - There are many apps in `Applications` so Marta displays all of those and the entire window pane is full with Applications, and Marta displays those as "folders".
  - Dragging `Xcode.app` from right pane to left pane, Marta will drag the file from Downloads and in to *inside* on of the Applications, the one under your mouse when you 'drop' the file. How to make this more logical?

2. **Tree structure**. Showing directories as a tree structure is a very powerful feature. Any plans for implementing a tree structure? Any plugins attempt to do this yet?

3. **iTerm integration**. Open folder in iTerm from Marta, open folder in Marta upon `cd` in iTerm; perhaps also (later) follow `ssh` via `sftp` or similar using already-installed ssh-keys in `~/.ssh`?

4. **Open two folders as cmd line parameter** e.g. keeping the leftmost, but change the rightmost e.g. `$ marta -rightpane "/Volumes/4TB_NVMe/"` keeping the left pane intact. 

5. **remove default keybindings** I'm using the F-keys for system-wide macros, how can I de-couple Marta from these keybindings? In VSCode, you add a minus, that way you can see that the user have overridden a system keybinding.
  - Perhaps a way to just start blank, i.e. there are no keybindings. Let me add them one by one, as I learn and see how Marta works, also a great way to learn about the actions like how `core.shift.*` etcetera works. 

6. **Multiple keybindings** If you assign multiple hotkeys to the same action, it appears indeterminate which of those the Action Bar on the bottom displays. Is it possible to override this somehow? Perhaps if "core.do.nothing" is assigned, the key binding is not consumed by the process and allowed to relay to the system utilities?

7. **Drag columns to resize** e.g. drag to resize size/name/modified columns? [low priority]

8. **FEATURE REQUEST: Favourites Bar instead of Action Bar** or perhaps combine these:
  - if the Action Bar configurable have favourite folders displayed permanently on the bottom, or
  - have the Action Bar as now, but have an option to permanently dock the Favourites-list to the left or right side of the Marta window, and being able to drag, drop and select those folders like regular folders in either pane.  (Edit: might be considered a duplicate of [#320](https://github.com/marta-file-manager/marta-issues/issues/320)).

9. **Current folder** There is an option to show `previous folder` as `..` but any option to also include "current folder" as `.` just a dot? Could be very useful, especially when using the mouse to drag files from paneA to paneB when paneB is populated with Applications only. 

10. **FEATURE REQUEST: Column Mode**. I realize I really miss Finders "columns" mode. 
![Screenshot of Finder (16-09-2019, 15-52-59)](https://user-images.githubusercontent.com/193781/64963771-162b2400-d89a-11e9-896a-76aa2c226c06.png)

**Comment by yanex** [comment]
> Dragging Xcode.app from right pane to left pane, Marta will drag the file from Downloads and in to inside on of the Applications, the one under your mouse when you 'drop' the file. How to make this more logical?

You are right, it doesn't make sense to move one application bundle inside another. I created #576 and will include a fix into the next release (0.7.1).

> Showing directories as a tree structure is a very powerful feature. Any plans for implementing a tree structure?

There are no immediate plans to implement tree structure view. However, I created #577 to track the issue.

> Open folder in iTerm from Marta, open folder in Marta upon cd in iTerm; perhaps also (later) follow ssh via sftp or similar using already-installed ssh-keys in ~/.ssh?

I suppose that this have to be supported both by the file manager and by the shell. Are you aware of similar solutions?
By the way, the embedded terminal in Marta already supports both-way current directory sync.

> Open two folders as cmd line parameter e.g. keeping the leftmost, but change the rightmost e.g. $ marta -rightpane "/Volumes/4TB_NVMe/" keeping the left pane intact.

Marta has some basic [command-line support](https://marta.yanex.org/docs/#using-from-command-line). Instead of extending it with a long list of flags for all occasions, I think it makes sense to create just one additional option – for running an action with a given identifier and arguments. This way it will be possible to support all of this scenarios by writing Lua plugins.
I created #578 and #579 for this.

> I'm using the F-keys for system-wide macros, how can I de-couple Marta from these keybindings?

You can reset a keybinding by providing `null` instead of an action id:
```
keyBindings {   
    "F1" null
}
```

> Drag columns to resize e.g. drag to resize size/name/modified columns?

You can actually resize columns with a mouse. The last column, however, always sticks to the right.

> if the Action Bar configurable have favourite folders displayed permanently on the bottom, or

Action bar is configurable – you can add your own buttons. It doesn't support passing action arguments, though, so you will need to add wrapper actions by writing a plugin.

> have the Action Bar as now, but have an option to permanently dock the Favourites-list to the left or right side of the Marta window

A lot of people ask this functionality. I think there will be a sidebar in some of the future versions.
It will be a shame to use it only for the favorites list, though. Probably, there should be an ability to put custom things into it (widgets? notifications? paste box?).

> Column Mode. I realize I really miss Finders "columns" mode
This is called [Miller columns](https://en.wikipedia.org/wiki/Miller_columns) :) There are no immediate plans for supporting it as well. Created a feature request (#580).
