### ISSUE TITLE
Can not move, Cross-device link

### ISSUE THREAD

**Issue by ay4** [marta-file-manager/marta-issues#571]
As I am trying to move files, I am getting an error message 'Could not move "FILENAME" Cross-device link. This happens iff source and destination are in different APFS containers (one in 'SSD', the other in 'ayBox'). 

I am using Marta 0.7 on macOS 10.14.6

![Screenshot 2019-09-16 at 18 00 47](https://user-images.githubusercontent.com/1137446/64973986-48458180-d8ac-11e9-8f20-a354967a4ec5.png)

**Comment by JanVanRyswyck** [comment]
I'm having the exact same issue after updating to 0.7.

**Comment by localhost** [comment]
Since version 0.7 I'm also having the same issue when trying to move files from my internal SSD to an external HDD. It happens regardless of filetype and downloaded or newly created files. Copying and deleting afterwards works fine.

It doesn't happen when I move the files to a different path within the same partition.

Internal filesystem: APFS
External filesystem: ExFAT
