### ISSUE TITLE
Open source marta

### ISSUE THREAD

**Issue by caelwithcats** [marta-file-manager/marta-issues#670]
I know this is a duplicate #194 but I think really think you should open source it.

If your on GitHub your expected to use it to release your source code. You don't have maintain to have pull requests. Just release the source code and add a notice saying "this repository will not accept pull requests".

If someone wants to add a feature they can fork it and make their own version of it. 

[Open source](https://en.wikipedia.org/wiki/The_Free_Software_Definition) gives you the right to change, study it, see how it works and redistribute/share it

Please open source marta 🥺

**Comment by yanex** [comment]
Hello, @caelwithcats,

Sorry for being short. Nothing changed since I explained my opinion in #194.

I don't know a sustainable way to get revenue from a small open-source project similar to Marta. If there was a Robin Hood that covered development costs at least partially (and still allowed me to drive the project the direction I prefer), I surely won't mind open-sourcing Marta. But it's extremely unlikely to happen, I think.

**Comment by caelwithcats** [comment]
@yanex what about GitHub sponsors
