### ISSUE TITLE
[Bug] Selection blinking, not possible to navigate

### ISSUE THREAD

**Issue by DmytroSokhach** [marta-file-manager/marta-issues#737]
Recently started getting this "blinking" issue. I don't have custom settings as got the laptop 3 weeks ago.
1. Not possible to scroll with niether keyboard or mouse wheel
2. Not possible to move cursor to item other than glitchy one
3. Happens independently of folder

https://user-images.githubusercontent.com/2741620/115418584-e40e4080-a1f9-11eb-9162-e65fe80f6e11.mov

**Comment by yanex** [comment]
Oh, that definitely looks terrible.

I suspect this blinking might happen because the directory is reloaded indefinitely for some reason.
By default, Marta sets up a file watcher on entering a folder and reloads the file list automatically when some file changes in the folder. You can check if it's the case by disabling the file watcher:

```
behavior {
    files {
        fileWatcher false
    }
}
```

If you disable the file watcher and restart Marta, there should be no blinking.

However, even it's the case, it doesn't answer the question what exactly is changing all the time. I suggest checking the "Disk" tab in [Activity Monitor](https://support.apple.com/guide/activity-monitor/welcome/mac). Also, if there's a hanging process that continuously writes something to the disk, restarting a Mac might help.

**Comment by DmytroSokhach** [comment]
@yanex Thank you for reply.
I will give a try with setting during working day and update here.
Thanks for pointing to Activity Monitor.

**Comment by DmytroSokhach** [comment]
I was observing for last couple days and it is now behaves fine.
I haven't used the suggestion from above, cause issue stopped reproducing.

Maybe I'm connecting the wrong dots or going paranoid, but let me explain:
1. Whole last week I had issues with Jabra Evolve 65 Duo connected to MacBook Pro 19 via bluetooth (without USB dongles), it was keeping disconnected all the time
2. During weekend I've "Reset Mac’s Bluetooth Module" using this [article](https://www.idownloadblog.com/2016/02/01/experiencing-bluetooth-problems-on-your-mac-try-this/#:~:text=To%20reset%20your%20Mac%27s%20Bluetooth,from%20all%20paired%20Bluetooth%20devices)
3. Haven't seen any issues since that.

**Comment by DmytroSokhach** [comment]
Not happening for me anymore. Closing the issue.

**Comment by DmytroSokhach** [comment]
@yanex I've experienced the same again today.
Your suggestion above worked immediately:
```
behavior {
    files {
        fileWatcher false
    }
}
```
And for the note, mumbo jumbo with reboot + bluetooth reset gave no effect.
